import { EMAIL } from "./profile";

export type Lang = "fr" | "en";
export type Bi = { fr: string; en: string };
export type Text = string | Bi;

export const b = (fr: string, en: string): Bi => ({ fr, en });
export const pick = (v: Text, lang: Lang) => (typeof v === "string" ? v : v[lang]);

export const T = {
  fr: {
    nav: ["À propos", "Services", "Compétences", "Réalisations", "Parcours", "Contact"],
    cta: "Me contacter",
    langLabel: "Langue",
    pitch:
      "Je conçois des architectures logicielles robustes, je pilote leur livraison et j'y intègre l'IA, là où elle résout un vrai problème.",
    btnWork: "Voir mes réalisations",
    btnCv: "Télécharger mon CV",
    aboutT: "À propos",
    aboutP: [
      "Je suis product engineer et chef de projet IT, basé à Nairobi. Chez Walumo, je dirige depuis mars 2026 la refonte de Talent Pro HR, une application RH que nous avons livrée en 5 mois, alors que la version précédente avait demandé 3 ans.",
      "En parallèle, chez ITM Holding, j'intègre des modèles d'IA dans des applications internes et j'automatise des processus avec Power Platform. Avant cela, j'ai développé des applications web et mobiles pour Orange RDC, la SNEL et Illumination Metaverse.",
      "J'ai commencé en 2021 comme testeur QA chez uTest. Pendant mon master en conception des systèmes d'information à l'UPN Kinshasa, j'ai prototypé MedGuard, un bracelet de suivi médical relié à un tableau de bord ThingsBoard.",
    ],
    infoK: ["Nom", "Email", "Localisation", "Langues", "Disponibilité"],
    infoV: ["Josué Kristo", EMAIL, "Nairobi, Kenya, travail à distance", "Français, lingala, anglais", "Missions et collaborations"],
    servT: "Services",
    forCompanies: "Entreprises",
    smeK: "PME",
    smeT: "Assistants WhatsApp et automatisations IA",
    smeP: "Chaque outil est conçu à partir de vos processus et de vos clients.",
    smeFor: "Pour les cabinets, cliniques, agences immobilières et de voyage, écoles privées, PME et startups.",
    smeCta: "Parlons de votre besoin",
    chatName: "Assistant de votre entreprise",
    chatSub: "WhatsApp",
    chat: [
      "Bonjour, vous êtes ouverts samedi ?",
      "Bonjour ! Oui, samedi matin. Souhaitez-vous prendre rendez-vous ?",
      "Oui, vers 10 h si possible.",
      "C’est noté pour samedi 10 h. Vous recevrez une confirmation ici.",
    ],
    chatNote: "Exemple de conversation",
    skillsT: "Compétences",
    workT: "Réalisations",
    filterLabel: "Filtre",
    caseBtn: "Voir l'étude de cas",
    codeBtn: "Code source",
    conf: "Confidentiel",
    accessLevels: "5 niveaux de droits d'accès",
    bracelet: "Bracelet",
    sensors: "Capteurs",
    hr: "FC",
    cvFields: ["Identité", "Expériences", "Compétences", "Formation"],
    methodT: "Méthode",
    journeyT: "Parcours",
    certT: "Certifications",
    eduT: "Formation",
    now: "aujourd'hui",
    contactT: "Contact",
    contactP: "Pour un poste, une mission ou un projet pour votre entreprise, écrivez-moi par email ou avec le formulaire.",
    infoLoc: "Localisation",
    refs: "Références disponibles sur demande.",
    fName: "Nom",
    fType: "Type de demande",
    fMsgPh: "Votre besoin, le contexte et les délais",
    send: "Envoyer le message",
    sentT: "Message envoyé",
    sentP: "Merci. Je vous réponds par email.",
    again: "Écrire un autre message",
    types: ["Recrutement", "Projet pour mon entreprise", "Autre"],
    quickLinks: "Liens rapides",
    close: "Fermer",
  },
  en: {
    nav: ["About", "Services", "Skills", "Work", "Experience", "Contact"],
    cta: "Contact me",
    langLabel: "Language",
    pitch: "I design robust software architectures, lead their delivery, and integrate AI where it solves a real problem.",
    btnWork: "See my work",
    btnCv: "Download my CV",
    aboutT: "About",
    aboutP: [
      "I'm a product engineer and IT project manager based in Nairobi. Since March 2026 I have led the rebuild of Talent Pro HR at Walumo, an HR application we shipped in 5 months. The previous version took 3 years.",
      "Alongside that, at ITM Holding, I integrate AI models into internal applications and automate processes with Power Platform. Before that I built web and mobile applications for Orange RDC, SNEL and Illumination Metaverse.",
      "I started in 2021 as a QA tester at uTest. During my master's in Information Systems Design at UPN Kinshasa, I prototyped MedGuard, a medical monitoring bracelet connected to a ThingsBoard dashboard.",
    ],
    infoK: ["Name", "Email", "Location", "Languages", "Availability"],
    infoV: ["Josué Kristo", EMAIL, "Nairobi, Kenya, remote", "French, Lingala, English", "Projects and collaborations"],
    servT: "Services",
    forCompanies: "Companies",
    smeK: "Small businesses",
    smeT: "WhatsApp assistants and AI automation",
    smeP: "Each tool is designed around your processes and your customers.",
    smeFor: "For law and accounting firms, clinics, real-estate and travel agencies, private schools, SMEs and startups.",
    smeCta: "Tell me what you need",
    chatName: "Your business assistant",
    chatSub: "WhatsApp",
    chat: [
      "Hi, are you open on Saturday?",
      "Hello! Yes, Saturday morning. Would you like to book an appointment?",
      "Yes, around 10am if possible.",
      "Booked for Saturday at 10am. You’ll get a confirmation here.",
    ],
    chatNote: "Sample conversation",
    skillsT: "Skills",
    workT: "Work",
    filterLabel: "Filter",
    caseBtn: "Read the case study",
    codeBtn: "Source code",
    conf: "Confidential",
    accessLevels: "5 levels of access rights",
    bracelet: "Bracelet",
    sensors: "Sensors",
    hr: "HR",
    cvFields: ["Identity", "Experience", "Skills", "Education"],
    methodT: "Method",
    journeyT: "Experience",
    certT: "Certifications",
    eduT: "Education",
    now: "present",
    contactT: "Contact",
    contactP: "For a role, a contract or a project for your business, email me or use the form.",
    infoLoc: "Location",
    refs: "References available on request.",
    fName: "Name",
    fType: "Request type",
    fMsgPh: "What you need, the context and the timeline",
    send: "Send message",
    sentT: "Message sent",
    sentP: "Thank you. I'll reply by email.",
    again: "Write another message",
    types: ["Hiring", "A project for my business", "Other"],
    quickLinks: "Quick links",
    close: "Close",
  },
};
export type Dict = (typeof T)["fr"];
