import { EMAIL } from "./profile";

export type Lang = "fr" | "en";
export type Bi = { fr: string; en: string };
export type Text = string | Bi;

export const b = (fr: string, en: string): Bi => ({ fr, en });
export const pick = (v: Text, lang: Lang) => (typeof v === "string" ? v : v[lang]);

export const T = {
  fr: {
    nav: ["À propos", "Services", "Compétences", "Réalisations", "Parcours", "Contact"],
    cta: "Parlons-en",
    langLabel: "Langue",
    pitch:
      "Je conçois des architectures logicielles robustes, je pilote leur livraison et j'y intègre l'IA, là où elle résout un vrai problème.",
    btnWork: "Voir mes réalisations",
    btnCv: "Télécharger mon CV",
    aboutT: "Un système rigoureux, et le sens de l'écart juste.",
    aboutP:
      "Product engineer et chef de projet IT certifié Google AI. Je conçois des architectures complexes, je mène des refontes complètes de produits numériques et j'intègre l'IA dans des applications métier, avec une obsession : livrer vite sans sacrifier la solidité. Mon parcours va du web à l'IA, jusqu'à l'IoT appliqué à la santé.",
    infoK: ["Nom", "Email", "Localisation", "Langues", "Disponibilité"],
    infoV: ["Josué Kristo", EMAIL, "Nairobi, Kenya · travail à distance", "Français, lingala, anglais", "Missions et collaborations"],
    servT: "Ce que je construis",
    forCompanies: "Pour les entreprises",
    smeK: "Pour les PME",
    smeT: "Des outils IA conçus pour votre entreprise",
    smeP: "Conception sur mesure, pas de produit tout fait : je pars de vos processus et de vos clients pour construire l'outil dont vous avez réellement besoin.",
    smeFor: "Pour :",
    smeCta: "Parlons de votre besoin",
    chatName: "Assistant · Votre entreprise",
    chatSub: "WhatsApp · exemple illustratif",
    chat: [
      "Bonjour, vous êtes ouverts samedi ?",
      "Bonjour ! Oui, samedi matin. Souhaitez-vous prendre rendez-vous ?",
      "Oui, vers 10 h si possible.",
      "C’est noté pour samedi 10 h. Vous recevrez une confirmation ici.",
    ],
    chatNote: "Exemple de conversation",
    skillsT: "Compétences et technologies",
    workT: "Des produits livrés, des prototypes qui prouvent.",
    filterLabel: "Filtre",
    caseBtn: "Voir l'étude de cas",
    codeBtn: "Code source",
    conf: "Confidentiel",
    accessLevels: "5 niveaux de droits d'accès",
    bracelet: "Bracelet",
    sensors: "Capteurs",
    hr: "FC",
    cvFields: ["Identité", "Expériences", "Compétences", "Formation"],
    methodK: "Méthode",
    methodT: "Ma méthode",
    journeyT: "Du test logiciel à la direction produit.",
    certT: "Certifications",
    eduT: "Formation",
    now: "aujourd'hui",
    contactT: "Construisons quelque chose de solide",
    contactP: "Un poste à pourvoir, un projet pour votre entreprise ou une idée à confronter au réel : écrivez-moi.",
    infoLoc: "Localisation",
    refs: "Références disponibles sur demande",
    fName: "Nom",
    fType: "Type de demande",
    fMsgPh: "Décrivez votre besoin, votre contexte, vos délais…",
    send: "Envoyer le message",
    sentT: "Merci, message envoyé.",
    sentP: "Je reviens vers vous rapidement.",
    again: "Écrire un autre message",
    types: ["Recrutement", "Projet pour mon entreprise", "Autre"],
    quickLinks: "Liens rapides",
    close: "Fermer",
  },
  en: {
    nav: ["About", "Services", "Skills", "Work", "Experience", "Contact"],
    cta: "Let's talk",
    langLabel: "Language",
    pitch: "I design robust software architectures, lead them all the way to delivery, and bring in AI where it solves a real problem.",
    btnWork: "See my work",
    btnCv: "Download my CV",
    aboutT: "A rigorous system — and a feel for where to break the rule.",
    aboutP:
      "Product engineer and IT project manager, Google AI certified. I design complex architectures, lead full rebuilds of digital products and integrate AI into business applications — with one obsession: ship fast without trading away robustness. My path runs from the web to AI, all the way to IoT for healthcare.",
    infoK: ["Name", "Email", "Location", "Languages", "Availability"],
    infoV: ["Josué Kristo", EMAIL, "Nairobi, Kenya · remote", "French, Lingala, English", "Projects and collaborations"],
    servT: "What I build",
    forCompanies: "For companies",
    smeK: "For small businesses",
    smeT: "AI tools built around your business",
    smeP: "Custom-built, not off-the-shelf: I start from how you work and who your customers are, then build the tool you actually need.",
    smeFor: "For:",
    smeCta: "Tell me what you need",
    chatName: "Assistant · Your business",
    chatSub: "WhatsApp · illustrative example",
    chat: [
      "Hi, are you open on Saturday?",
      "Hello! Yes, Saturday morning. Would you like to book an appointment?",
      "Yes, around 10am if possible.",
      "Booked for Saturday at 10am. You’ll get a confirmation right here.",
    ],
    chatNote: "Sample conversation",
    skillsT: "Skills & technologies",
    workT: "Shipped products, and prototypes that prove a point.",
    filterLabel: "Filter",
    caseBtn: "Read the case study",
    codeBtn: "Source code",
    conf: "Confidential",
    accessLevels: "5 levels of access rights",
    bracelet: "Bracelet",
    sensors: "Sensors",
    hr: "HR",
    cvFields: ["Identity", "Experience", "Skills", "Education"],
    methodK: "Method",
    methodT: "How I work",
    journeyT: "From software testing to product leadership.",
    certT: "Certifications",
    eduT: "Education",
    now: "present",
    contactT: "Let's build something solid",
    contactP: "A role to fill, a project for your business, or an idea to pressure-test — write to me.",
    infoLoc: "Location",
    refs: "References available on request",
    fName: "Name",
    fType: "Request type",
    fMsgPh: "Tell me about your need, context and timeline…",
    send: "Send message",
    sentT: "Thanks — message sent.",
    sentP: "I'll get back to you shortly.",
    again: "Write another message",
    types: ["Hiring", "A project for my business", "Other"],
    quickLinks: "Quick links",
    close: "Close",
  },
};

export type Dict = (typeof T)["fr"];
